//! Everything `coverage/` and the generated documentation blocks contain,
//! computed in memory so `check` can compare it with what is committed.

use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

use crate::model::{component_label, Unit, UnitsFile, COMPONENTS};
use crate::status::{pct, Counts, State, Status, Summary};
use crate::treemap::{self, Metric};

pub const GENERATED_NOTE: &str =
    "<!-- Generated by `cargo run -p megabase-coverage -- update`; edits are overwritten and CI rejects drift. -->";

/// Generated files, plus marker blocks to splice into hand-written files.
#[derive(Default)]
pub struct Outputs {
    pub files: BTreeMap<PathBuf, String>,
    pub blocks: Vec<(PathBuf, &'static str, String)>,
    /// Directories whose files must all be generated ones.
    pub owned_dirs: Vec<(PathBuf, &'static str)>,
}

/// Megabase palette (docs/brand/README.md): neutral 100 label, green value.
const BADGE_LABEL: &str = "#181A1D";
const MONO: &str = "JetBrains Mono,IBM Plex Mono,SFMono-Regular,Menlo,Consolas,monospace";

fn badge_color(percent: f64) -> &'static str {
    match percent {
        p if p >= 90.0 => "#00D892",
        p if p >= 50.0 => "#009366",
        p if p > 0.0 => "#005441",
        _ => "#303235",
    }
}

fn badge_text(fill: &str) -> &'static str {
    if fill == "#00D892" {
        "#0B0E12"
    } else {
        "#F7F7F7"
    }
}

/// Monospace advance at 11px.
fn text_width(s: &str) -> f64 {
    s.chars().count() as f64 * 6.6
}

/// A flat badge in the shields.io layout, drawn in the Megabase palette.
pub fn badge(label: &str, value: &str, color: &str) -> String {
    let lw = (text_width(label) + 12.0).round();
    let vw = (text_width(value) + 12.0).round();
    let w = lw + vw;
    let text = badge_text(color);
    format!(
        concat!(
            r##"<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="20" role="img" aria-label="{label}: {value}">"##,
            r##"<title>{label}: {value}</title>"##,
            r##"<clipPath id="r"><rect width="{w}" height="20" rx="3"/></clipPath>"##,
            r##"<g clip-path="url(#r)"><rect width="{lw}" height="20" fill="{label_bg}"/><rect x="{lw}" width="{vw}" height="20" fill="{color}"/></g>"##,
            r##"<g text-anchor="middle" font-family="{mono}" font-size="11">"##,
            r##"<text x="{lx}" y="14" fill="#BABABB">{label}</text>"##,
            r##"<text x="{vx}" y="14" fill="{text}">{value}</text>"##,
            "</g></svg>\n"
        ),
        w = w,
        lw = lw,
        vw = vw,
        lx = lw / 2.0,
        vx = lw + vw / 2.0,
        label = label,
        value = value,
        color = color,
        text = text,
        label_bg = BADGE_LABEL,
        mono = MONO,
    )
}

fn levels(units: &[&Unit]) -> String {
    let min = units.iter().map(|u| u.level).min().unwrap_or(0);
    let max = units.iter().map(|u| u.level).max().unwrap_or(0);
    if min == max {
        format!("{min}")
    } else {
        format!("{min}–{max}")
    }
}

pub fn render(units: &UnitsFile, status: &Status, summary: &Summary) -> Result<Outputs> {
    let mut out = Outputs::default();
    let cov = PathBuf::from("coverage");
    let mut units_json = serde_json::to_string_pretty(units)?;
    units_json.push('\n');
    out.files.insert(cov.join("units.json"), units_json);
    let mut summary_json = serde_json::to_string_pretty(summary)?;
    summary_json.push('\n');
    out.files.insert(cov.join("summary.json"), summary_json);
    out.owned_dirs.push((cov.clone(), ".svg"));

    let all: Vec<&Unit> = units.units.iter().collect();
    out.files.insert(
        cov.join("treemap.svg"),
        treemap::render(
            treemap::Heading::Status,
            &all,
            status,
            Metric::State,
            1280.0,
            treemap::Theme::Dark,
        ),
    );
    out.files.insert(
        cov.join("treemap-light.svg"),
        treemap::render(
            treemap::Heading::Status,
            &all,
            status,
            Metric::State,
            1280.0,
            treemap::Theme::Light,
        ),
    );
    for (name, title, metric) in [
        (
            "treemap-coverage.svg",
            "Coverage (implemented units)",
            Metric::Coverage,
        ),
        (
            "treemap-conformance.svg",
            "Conformance (judge-verified units)",
            Metric::Conformance,
        ),
    ] {
        out.files.insert(
            cov.join(name),
            treemap::render(
                treemap::Heading::Title(title.into()),
                &all,
                status,
                metric,
                1280.0,
                treemap::Theme::Dark,
            ),
        );
    }
    for (id, label) in COMPONENTS {
        let members: Vec<&Unit> = all.iter().copied().filter(|u| u.component == *id).collect();
        out.files.insert(
            cov.join(format!("treemap-{id}.svg")),
            treemap::render(
                treemap::Heading::Title((*label).into()),
                &members,
                status,
                Metric::State,
                900.0,
                treemap::Theme::Dark,
            ),
        );
        let c = &summary.components[*id].counts;
        let p = pct(c.conformant, c.units);
        out.files.insert(
            cov.join(format!("badge-{id}.svg")),
            badge(
                label,
                &format!("{p}% ({}/{})", c.conformant, c.units),
                badge_color(p),
            ),
        );
    }
    let t = &summary.totals;
    let badges = [
        (
            "badge-coverage.svg",
            "coverage",
            summary.percent.coverage,
            format!("{}%", summary.percent.coverage),
        ),
        (
            "badge-conformance.svg",
            "conformance",
            summary.percent.conformance,
            format!(
                "{}% ({}/{} cases)",
                summary.percent.conformance, summary.judge.passing, summary.judge.cases
            ),
        ),
        (
            "badge-done.svg",
            "done",
            summary.percent.done,
            format!("{}%", summary.percent.done),
        ),
    ];
    for (file, label, p, value) in badges {
        out.files
            .insert(cov.join(file), badge(label, &value, badge_color(p)));
    }
    out.files.insert(
        cov.join("badge-units.svg"),
        badge("units", &t.units.to_string(), "#303235"),
    );
    // README banners live in docs/brand/ as Kite assets. Coverage must not
    // overwrite them: float formatting differs across rustc, and Kite wins
    // on visual design (GOAL.md).

    out.blocks
        .push(("README.md".into(), "status", readme_status(units, summary)));
    out.blocks
        .push(("docs/COMPATIBILITY.md".into(), "pins", pins_table(units)));
    out.blocks.push((
        "docs/COMPATIBILITY.md".into(),
        "units",
        compatibility_units(units, summary),
    ));
    out.blocks
        .push(("PROGRESS.md".into(), "pins", pins_table(units)));
    out.blocks
        .push(("PROGRESS.md".into(), "status", progress_status(summary)));

    let epic_dir = PathBuf::from("docs/epics/level-1");
    out.owned_dirs.push((epic_dir.clone(), ".md"));
    for (file, body) in epics(units, status) {
        out.files.insert(epic_dir.join(file), body);
    }
    Ok(out)
}

fn readme_status(units: &UnitsFile, summary: &Summary) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "{GENERATED_NOTE}\n");
    let _ = writeln!(
        s,
        "<picture>\n  <source media=\"(prefers-color-scheme: light)\" srcset=\"coverage/treemap-light.svg\">\n  <img src=\"coverage/treemap.svg\" alt=\"Supabase components: {:.1}% conformant ({}/{})\" width=\"100%\">\n</picture>\n",
        summary.percent.done,
        summary.totals.conformant,
        summary.totals.units
    );
    let _ = writeln!(
        s,
        "<sup>**How the denominator is computed.** `coverage/units.json` lists {} units extracted from the pinned sources in `vendor/` \
(see [`vendor.toml`](vendor.toml)) by `tools/megabase-coverage`: every gateway-reachable route, PostgREST query operator, \
`Prefer` value and media type, Auth grant type, OAuth provider and verification type, Realtime message type, Storage and \
Postgres Meta endpoint, Edge Runtime op, Supavisor endpoint and pool mode, Studio project page and API route, and the \
`auth`/`storage` SQL objects apps depend on. Each unit records its upstream file and line. {} upstream items are excluded \
with a recorded reason (blocked or unexposed by the gateway, hosted-platform pages, documentation UIs); see \
[`docs/COMPATIBILITY.md`](docs/COMPATIBILITY.md). A unit is *implemented* when Megabase code claims it, *tested* when a \
judge case covers it, and *conformant* when every such case matches the reference stack. Coverage = implemented ÷ units; \
conformance = identical judge cases ÷ judge cases; component percentages count conformant units. The website Status page \
embeds the same generated treemap (`coverage/treemap.svg`, light: `coverage/treemap-light.svg`).</sup>\n",
        units.total,
        units.excluded.len()
    );
    let _ = writeln!(
        s,
        "**Verified apps:** [docs/VERIFIED_APPS.md](docs/VERIFIED_APPS.md) (none yet). [Submit an app](https://github.com/Zouhairmaj/megabase/issues/new?labels=type:investigation)."
    );
    s
}

fn pins_table(units: &UnitsFile) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "{GENERATED_NOTE}\n");
    let _ = writeln!(
        s,
        "| Upstream | Path | Tag | Commit | License | Reference image |"
    );
    let _ = writeln!(s, "|---|---|---|---|---|---|");
    for p in &units.vendor {
        let _ = writeln!(
            s,
            "| [{}]({}) | `{}` | `{}` | `{}` | {} | {} |",
            p.name,
            p.repo,
            p.path,
            p.tag,
            p.commit,
            p.license,
            p.image
                .as_deref()
                .map_or("—".to_string(), |i| format!("`{i}`"))
        );
    }
    s
}

fn compatibility_units(units: &UnitsFile, summary: &Summary) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "{GENERATED_NOTE}\n");
    let _ = writeln!(
        s,
        "In scope: **{} units**. Excluded: **{}** upstream items.\n",
        units.total,
        units.excluded.len()
    );
    let _ = writeln!(
        s,
        "| Component | Group | Level | Units | Implemented | Tested | Conformant |"
    );
    let _ = writeln!(s, "|---|---|---|---:|---:|---:|---:|");
    for (id, label) in COMPONENTS {
        let groups = &summary.components[*id].groups;
        for (group, c) in groups {
            let members: Vec<&Unit> = units
                .units
                .iter()
                .filter(|u| u.component == *id && &u.group == group)
                .collect();
            let _ = writeln!(
                s,
                "| {label} | {group} | {} | {} | {} | {} | {} |",
                levels(&members),
                c.units,
                c.implemented,
                c.tested,
                c.conformant
            );
        }
    }
    let _ = writeln!(s, "\n#### Excluded upstream items\n");
    let mut reasons: BTreeMap<(&str, &str), usize> = BTreeMap::new();
    for e in &units.excluded {
        *reasons
            .entry((e.component.as_str(), e.reason.as_str()))
            .or_default() += 1;
    }
    let _ = writeln!(s, "| Component | Reason | Items |");
    let _ = writeln!(s, "|---|---|---:|");
    for ((component, reason), n) in reasons {
        let _ = writeln!(s, "| {} | {reason} | {n} |", component_label(component));
    }
    let _ = writeln!(s, "\n<details>\n<summary>Full list</summary>\n");
    for e in &units.excluded {
        let _ = writeln!(
            s,
            "- {}: `{}` ({}:`{}`:{}) — {}",
            component_label(&e.component),
            e.name,
            e.source.repo,
            e.source.file,
            e.source.line,
            e.reason
        );
    }
    let _ = writeln!(s, "\n</details>");
    s
}

fn progress_status(summary: &Summary) -> String {
    let t: &Counts = &summary.totals;
    let mut s = String::new();
    let _ = writeln!(s, "{GENERATED_NOTE}\n");
    let _ = writeln!(
        s,
        "- Units: {} (implemented {}, tested {}, conformant {})",
        t.units, t.implemented, t.tested, t.conformant
    );
    let _ = writeln!(
        s,
        "- Coverage {}% · conformance {}% ({}/{} judge cases) · done {}%",
        summary.percent.coverage,
        summary.percent.conformance,
        summary.judge.passing,
        summary.judge.cases,
        summary.percent.done
    );
    s
}

fn epics(units: &UnitsFile, status: &Status) -> Vec<(String, String)> {
    let mut groups: BTreeMap<(usize, &str, &str), Vec<&Unit>> = BTreeMap::new();
    for unit in units.units.iter().filter(|u| u.level == 1) {
        let order = COMPONENTS
            .iter()
            .position(|(c, _)| *c == unit.component)
            .unwrap_or(99);
        groups
            .entry((order, unit.component.as_str(), unit.group.as_str()))
            .or_default()
            .push(unit);
    }
    let pins: BTreeMap<&str, &str> = units
        .vendor
        .iter()
        .map(|p| (p.name.as_str(), p.repo.as_str()))
        .collect();
    let tags: BTreeMap<&str, &str> = units
        .vendor
        .iter()
        .map(|p| (p.name.as_str(), p.commit.as_str()))
        .collect();
    groups
        .into_iter()
        .map(|((_, component, group), members)| {
            let label = component_label(component);
            let mut s = String::new();
            let _ = writeln!(s, "# {label}: {group}\n");
            let _ = writeln!(s, "{GENERATED_NOTE}\n");
            let _ = writeln!(s, "- Milestone: Level 1");
            let _ = writeln!(s, "- Labels: `component:{component}`, `level:1`, `type:feature`");
            let _ = writeln!(s, "- Units: {}\n", members.len());
            let _ = writeln!(
                s,
                "Specs go in `specs/{component}/<unit>.md` (GOAL.md section 5). Mark served code with \
`// megabase:unit <id>` and add judge cases in `judge/cases/` listing the unit ids.\n"
            );
            let _ = writeln!(s, "| State | Unit id | Upstream source |");
            let _ = writeln!(s, "|---|---|---|");
            for u in members {
                let state = match status.state(&u.id) {
                    State::Missing => "⬜",
                    State::Implemented => "🟨",
                    State::Tested => "🟩",
                    State::Conformant => "✅",
                };
                let link = match (pins.get(u.source.repo.as_str()), tags.get(u.source.repo.as_str())) {
                    (Some(repo), Some(commit)) => format!(
                        "[{}:{}]({repo}/blob/{commit}/{}#L{})",
                        u.source.file, u.source.line, u.source.file, u.source.line
                    ),
                    _ => format!("{}:{}", u.source.file, u.source.line),
                };
                let _ = writeln!(s, "| {state} | `{}` | {link} |", u.id);
            }
            (format!("{component}-{group}.md"), s)
        })
        .collect()
}

pub fn splice(text: &str, marker: &str, content: &str) -> Result<String> {
    let begin = format!("<!-- {marker}:begin -->");
    let end = format!("<!-- {marker}:end -->");
    let start = text
        .find(&begin)
        .with_context(|| format!("missing `{begin}` marker"))?;
    let stop = text
        .find(&end)
        .with_context(|| format!("missing `{end}` marker"))?;
    if stop < start {
        bail!("`{end}` comes before `{begin}`");
    }
    Ok(format!(
        "{}{begin}\n{content}{end}{}",
        &text[..start],
        &text[stop + end.len()..]
    ))
}

/// Applies `outputs` to the tree at `root` (`write`), or reports which paths
/// differ from it.
pub fn apply(root: &Path, outputs: &Outputs, write: bool) -> Result<Vec<String>> {
    let mut drift = Vec::new();
    let mut wanted: BTreeMap<PathBuf, String> = outputs.files.clone();
    for (file, marker, content) in &outputs.blocks {
        let base = match wanted.get(file) {
            Some(text) => text.clone(),
            None => std::fs::read_to_string(root.join(file))
                .with_context(|| format!("reading {}", file.display()))?,
        };
        wanted.insert(file.clone(), splice(&base, marker, content)?);
    }
    for (dir, ext) in &outputs.owned_dirs {
        let Ok(entries) = std::fs::read_dir(root.join(dir)) else {
            continue;
        };
        for entry in entries {
            let name = entry?.file_name().to_string_lossy().to_string();
            let rel = dir.join(&name);
            if name.ends_with(ext) && !wanted.contains_key(&rel) {
                drift.push(format!("{} (stale)", rel.display()));
                if write {
                    std::fs::remove_file(root.join(&rel))?;
                }
            }
        }
    }
    for (rel, content) in &wanted {
        let path = root.join(rel);
        let current = std::fs::read_to_string(&path).ok();
        if current.as_deref() != Some(content.as_str()) {
            drift.push(rel.display().to_string());
            if write {
                if let Some(parent) = path.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(&path, content)?;
            }
        }
    }
    Ok(drift)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn splice_replaces_only_the_block() {
        let text = "a\n<!-- x:begin -->\nold\n<!-- x:end -->\nb\n";
        assert_eq!(
            splice(text, "x", "new\n").unwrap(),
            "a\n<!-- x:begin -->\nnew\n<!-- x:end -->\nb\n"
        );
        assert!(splice("no markers", "x", "").is_err());
        assert!(splice("<!-- x:end -->\n<!-- x:begin -->", "x", "n").is_err());
    }

    fn sample_units() -> UnitsFile {
        use crate::model::{Collector, Pin, Source};
        let mut c = Collector::default();
        c.route(
            "rest",
            "resources",
            "GET",
            "/rest/v1/todos",
            1,
            Source {
                repo: "postgrest".into(),
                file: "ApiRequest.hs".into(),
                line: 10,
            },
        );
        c.exclude(
            "studio",
            "GET /sign-in".into(),
            "hosted-platform page",
            Source {
                repo: "supabase".into(),
                file: "pages/sign-in.tsx".into(),
                line: 1,
            },
        );
        c.finish(vec![Pin {
            name: "postgrest".into(),
            path: "vendor/postgrest".into(),
            repo: "https://github.com/PostgREST/postgrest".into(),
            tag: "v16".into(),
            commit: "abc".into(),
            license: "MIT".into(),
            image: Some("postgrest/postgrest:v16".into()),
        }])
    }

    #[test]
    fn badge_colors_follow_thresholds() {
        assert_eq!(badge_color(0.0), "#303235");
        assert_eq!(badge_color(10.0), "#005441");
        assert_eq!(badge_color(50.0), "#009366");
        assert_eq!(badge_color(90.0), "#00D892");
        let high = badge("coverage", "90%", badge_color(90.0));
        assert!(high.contains("#00D892"));
        assert!(high.contains("#0B0E12"));
    }

    #[test]
    fn render_and_apply_write_generated_files() {
        let units = sample_units();
        let status = Status {
            states: {
                let mut m = BTreeMap::new();
                m.insert("rest:route:GET /rest/v1/todos".into(), State::Implemented);
                m
            },
            cases_total: 0,
            cases_passing: 0,
        };
        let summary = crate::status::summarize(&units, &status);
        let outputs = render(&units, &status, &summary).unwrap();
        assert!(outputs.files.contains_key(Path::new("coverage/units.json")));
        assert!(outputs
            .files
            .contains_key(Path::new("coverage/badge-coverage.svg")));
        assert!(outputs
            .files
            .contains_key(Path::new("docs/epics/level-1/rest-resources.md")));
        let pins = outputs
            .blocks
            .iter()
            .find(|(_, m, _)| *m == "pins")
            .unwrap()
            .2
            .as_str();
        assert!(pins.contains("`postgrest/postgrest:v16`"));

        let tree = crate::scan::TempTree::new();
        tree.write(
            "README.md",
            "x\n<!-- status:begin -->\nold\n<!-- status:end -->\n",
        );
        tree.write(
            "docs/COMPATIBILITY.md",
            "<!-- pins:begin -->\n<!-- pins:end --><!-- units:begin -->\n<!-- units:end -->\n",
        );
        tree.write(
            "PROGRESS.md",
            "<!-- pins:begin -->\n<!-- pins:end --><!-- status:begin -->\n<!-- status:end -->\n",
        );
        tree.write("coverage/stale.svg", "<svg/>");
        let drift = apply(&tree.root, &outputs, false).unwrap();
        assert!(drift.iter().any(|p| p.contains("stale.svg")));
        apply(&tree.root, &outputs, true).unwrap();
        assert!(!tree.root.join("coverage/stale.svg").exists());
        assert!(tree.root.join("coverage/units.json").exists());
        let readme = std::fs::read_to_string(tree.root.join("README.md")).unwrap();
        assert!(readme.contains("How the denominator is computed"));
    }
}
