-- Judge fixtures: generated, non-personal data loaded into the reference
-- database at first start (GOAL.md rule 7). Judge cases rely on these exact
-- rows; change them only through the judge review branch.

create table public.todos (
  id bigint generated by default as identity primary key,
  title text not null,
  done boolean not null default false,
  priority int not null default 0
);

insert into public.todos (title, done, priority) values
  ('write the spec', true, 2),
  ('port the unit', false, 3),
  ('run the judge', false, 1);

alter table public.todos enable row level security;
create policy "todos are readable by everyone" on public.todos
  for select to anon, authenticated using (true);

grant select on public.todos to anon, authenticated;
grant all on public.todos to service_role;

create function public.add_numbers(a int, b int) returns int
  language sql immutable
  as $$ select a + b $$;

grant execute on function public.add_numbers(int, int) to anon, authenticated, service_role;

notify pgrst, 'reload schema';
